SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE "SALES" 
   (	"SALESRECORDID" NUMERIC, 
	"SALESDATE" DATE, 
	"SALESITEMID" NUMERIC, 
	"SALESPIECES" NUMERIC, 
	"SALESCOST" NUMERIC, 
	"ACTIVEFLAG" NUMERIC(1,0), 
	"SALESCUSTOMERID" NUMERIC, 
	"SALESREMARKS" VARCHAR(50)
   );